volumes:
  tracks-database:
    driver: local
    name: tracks-database

services:
  where-have-i-been-nginx:
    container_name: where-have-i-been-nginx
    image: nck974/where-have-i-been-nginx:1.0.1
    restart: unless-stopped
    depends_on:
      - where-have-i-been-rs
      - where-have-i-been-ng
    ports:
      - 443:443
      - 80:80
    environment:
      - NGINX_HOST=${SERVER_IP}
    volumes:
      - ./ssl/:/etc/nginx/ssl/:ro

  where-have-i-been-rs:
    container_name: where-have-i-been-rs
    image: nck974/where-have-i-been-rs:0.2.2
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - tracks-database:/app/data
      - ./data:/app/tracks-data
    environment:
      # Use this map to convert activity types to a common type
      ACTIVITY_TYPE_CONVERSIONS: |
        {
          "StandUpPaddling": "Stand Up Paddling",
          "IceSkate": "Ice Skate",
          "generic": "other",
          "hiking": "walking",
          "ebikeride": "cycling",
          "Biking": "cycling",
          "biking": "cycling",
          "1": "cycling",
          "Velomobile": "cycling"
        }

  where-have-i-been-ng:
    container_name: where-have-i-been-ng
    image: nck974/where-have-i-been-ng:0.1.2
    restart: unless-stopped
    environment:
      - BACKEND_URL=https://${SERVER_IP}/api
    ports:
      - 8080:80
